   
version: "3"

services:
    # Gitlab Service
    web:
      image: 'gitlab/gitlab-ce:latest'
      container_name: dc-gitlab
      restart: always
      hostname: 100.16.0.53
      ports:
        - '80:80'
        - '443:443'
        - '22:22'
      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'

    # Sonarqube Service
    sonarqube:
        image: sonarqube:8.2-community
        container_name: dc-sonarqube
        hostname: 100.16.0.53
        expose:
            - 9000
        ports:
            - '9000:9000'
        volumes:
            - '/home/xroot/sonarqube/logs:/opt/sonarqube/logs'
            - '/home/xroot/sonarqube/data:/opt/sonarqube/data'
            - '/home/xroot/sonarqube/conf:/opt/sonarqube/conf'
            - '/home/xroot/sonarqube/extensions:/opt/sonarqube/extensions'
