services:
    # Gitlab Service
    web:
      image: 'gitlab/gitlab-ce:latest'
      container_name: dc-gitlab
      restart: always
      hostname: 100.16.0.53
      ports:
        - '80:80'
        - '443:443'
        - '22:22'
      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'

    # Jenkins Service
    jenkins:
        image: "jenkins:2.60.3"
        ports:
          - "8080:8080"
        restart: "always"
        volumes:
          - "/home/xroot/data-jenkins:/var/jenkins_home"
