
version: "3"

services:

    # Jenkins Service
    jenkins:
        image: jenkins/jenkins:lts
        container_name: dc-jenkins
        ports:
            - "11080:8080"
        restart: "always"
        hostname: 100.16.0.53
        volumes:
            - "/home/xroot/data-jenkins:/var/jenkins_home"
