concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "SonarQube runner"
  url = "http://100.16.0.53"
  token = "JxncWFfeazv1SDm2BPp4"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]